services:
  pyneolink:
    build: .
    volumes:
      - ./config.json:/app/config.json:ro
      - ./.pyneolink_state.json:/app/.pyneolink_state.json
    ports:
      - "16577:16577/udp"
      - "8554:8554/tcp"
    command: ["--info", "--config", "config.json", "--camera", "Scherbaka 41 - Front"]

  pyneolink-hostnet:
    build: .
    network_mode: host
    volumes:
      - ./config.json:/app/config.json:ro
      - ./.pyneolink_state.json:/app/.pyneolink_state.json
    command: ["--info", "--config", "config.json", "--camera", "Scherbaka 41 - Front"]
